id: 'skyvoid_worldgen_empty'
name: 'Empty Sky Void'
author: 'BPR'
version: 2.0.1

require: 
  - src.plugins.worldgen.generate.base

data_pack:
  load: .
  
pipeline:
  - src.plugins.worldgen.get_empty_biomes.empty
  - src.plugins.worldgen.get_empty_structures.empty
